#!/bin/sh

# start a batch file, passing the appropriate config file option to runbatch

# ensure readable
umask 002

HERE="`echo $0 | sed -e 's/startbatch$//'`"
CONFFILE=$HERE/runbatch.conf

function usage () {
  echo "Usage: $0"
  echo "   or: $0 -f conffile"
  exit 3
}

if [ $# -eq 2 ]; then
  if [ $1 = '-f' ]; then
    CONFFILE=$2
  else
    usage
  fi
else if [ $# -ne 0 ]; then
  usage
fi
fi

if dialog --inputbox "Please enter a reason:" 20 70 2> /tmp/$$.dresult; then
    REASON=`cat /tmp/$$.dresult`
    rm /tmp/$$.dresult
    clear
    $HERE/runbatch $CONFFILE "$REASON" < /dev/null > startbatch.errs 2>&1 &
else
    clear
    echo "Cancelled.  No job killed."
fi

