#!/bin/sh

#CHECKDIR1=/auto/groups/tthee-scratch/check/check-2004-12-23T19:41:11+0000

CHECKDIR=/auto/groups/tthee-scratch/check/check-2004-12-16T20:04:23+0000


# file with lines "traceXXXX" for each trace in run, in run order
# (hand-edited from conf file)

TRACES=run_xmas_length_data.txt

# file with traceXXXX and st-time

cd  $CHECKDIR ; bin/mktraceindex --simple | grep -v INCOMPLETE > simple-non-incomplete.txt

cat simple-non-incomplete.txt |  cut -d' ' -f1,3 > /tmp/tm.$$
cat simple-non-incomplete.txt |  cut -d' ' -f1,4 > /tmp/st.$$

cd /homes/pes20/Net/TCP/Test/scripts/check/

./apply -default "-100000.0" -map /tmp/tm.$$ < $TRACES | cut -c6- | nl -v0 >/tmp/tmgraph.$$
./apply -default "-1000.0" -map /tmp/st.$$ < $TRACES | cut -c6- | nl -v0 >/tmp/stgraph.$$





# plot the resulting datasets, by position in run

TITLE="Wall-clock execution time in run_xmas.conf, by position in run"
cat <<EOF | gnuplot -persist
set terminal x11
set key below
set title "$TITLE"
set ylabel 'Execution time'
set xlabel 'Index in run'
plot '/tmp/tmgraph.$$' using 1:3  title "non-INCOMPLETE" with points pt 2 pointsize 1.0 ;
EOF

# plot the resulting datasets, by position in run

TITLE="Normalised execution time in run_xmas.conf, by position in run"
cat <<EOF | gnuplot -persist
set terminal x11
set key below
set title "$TITLE"
set ylabel 'Execution time'
set xlabel 'Index in run'
plot '/tmp/stgraph.$$' using 1:3  title "non-INCOMPLETE" with points pt 2 pointsize 1.0 ;
EOF
