(* hol_to_latex.ml -- turn .sml file into LaTeX code (with embedded typeset HOL) *)
(* Keith Wansbrough 2001-2004 *)

open Mngdump
open Holparse
open Holparsesupp
open Holparsetools

open Holdocmodel
open Holdoc_init

let (rendermosml_doc_content:mosml_content0->unit) =
  fun d -> match d with
      MosmlContent s -> ()
    | MosmlWhite s -> ()
    | MosmlStr s -> ()
    | MosmlIndent i -> ()
    | MosmlIdent (b,s) -> ()
    | MosmlHol(MosmlHolBT,d') -> wrap "\\showrule{" "}" renderholdoc d'; print_newline()
    | MosmlHol(MosmlHolBTBT,d') -> ()
    | MosmlText t -> ()
    | MosmlTex t -> rendertexdoc t
    | MosmlDir d -> match d with (d,_) -> do_directive d
;;

let (rendermosmldoc:mosmldoc->unit) =
  fun ds -> List.iter (fun (c,_) -> rendermosml_doc_content c) ds;;

(* -------------------------------------------------------------------- *)
(*  Main program                                                        *)
(* -------------------------------------------------------------------- *)

let _ =
  let doc = parse_fileargs ModeMosml mosml_main in
  (* NB: no trailing newline - we hope the first line of source is a comment already! *)
  print_string "%%%% AUTOGENERATED FILE (from MNG source) -- DO NOT EDIT! %%%% "; print_newline();
  try
    rendermosmldoc doc;
    dump_unseen_strings ()
  with
    BadArg e ->
      prerr_endline (format_badarg e)


