#!/bin/bash

TITLE=`basename $1`
grep ^==Step "$@" | cut -d' ' -f2 > /tmp/stepgraph.$$
cat <<EOF | gnuplot -persist
set title "$TITLE"
set ylabel 'Trace step'
set xlabel 'Checker attempt'
set nokey
plot '/tmp/stepgraph.$$';
EOF

