MAKE=$(MAKE) /F Makefile.win $(MAKEFLAGS)

all::
	cd parser_test
	$(MAKE) all
	cd ..
	cd common
	$(MAKE) all
	cd ..
	cd tthee
	$(MAKE) all
	cd ..

clean::
	cd parser_test
	$(MAKE) clean
	cd ..
	cd common
	$(MAKE) clean
	cd ..
	cd tthee
	$(MAKE) clean
	cd ..
