#!/bin/sh

OCAMLPATH=/usr/groups/netsem/ocaml/bin

export -p PATH=$OCAMLPATH:$PATH
export -p OCAMLPATH=$OCAMLPATH

# Build
cd /home/Net/TCP/Test
if ! make "$@" >build-log 2>&1; then
    exit 1
fi

# Set permission correctly on executables
chown root:wheel slurp/slurp
chmod +s slurp/slurp
chown root:wheel injector/injector
chmod +s injector/injector
chown root:wheel libd/libd
chmod +s libd/libd

